config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :articles
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true
    validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
                         uniqueness: { case_sensitive: false }, 
                         length: { minimum: 3, maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX },
                      length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in? 
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index
        @articles = Article.paginate(page: params[:page], per_page: 3)
    end
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfuly created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end
    
    def new
        @article = Article.new
    end
    
    def show
    end
    
    def edit
    end
    
    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfuly updated"
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @article.destroy
        flash[:success] = "Article was successfuly deleted"
        redirect_to articles_path
    end
    
    private
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    
    def require_same_user
        if current_user != @article.user and !current_user.admin
            flash[:danger] = "You can only edit or delete your own articles"
            redirect_to root_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, only: [:new, :create]
    
    def index 
        @categories = Category.paginate(page: params[:page], per_page: 3)
    end
    
    def show
        @category = Category.find(params[:id])
        @articles = @category.articles
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Successfully created new category"
            redirect_to categories_path
        else
            render 'new'
        end
    end
    
    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Successfuly updated category #{@category.name}"
            redirect_to categories_path
        else
            render 'edit'
        end
    end
    
    private
    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
        if !logged_in? || !current_user.admin?
            flash[:danger] = "Only admin is permited to create new categories"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    
    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = 'You have successfuly logged in'
            @current_user = user
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Log in failed. Wrong username or password"
            render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    
    def index
        @users = User.paginate(page: params[:page], per_page: 2)
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the blog, #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end
    
    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    def update
        if @user.update_attributes(user_params)
            flash[:success] = "Your account was updated successully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @user.destroy
        flash[:success] = "User and all articles created by user have been deleted"
        redirect_to root_path
    end
        
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:danger] = "You can only edit your own profile"
            redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? && !current_user.admin?
            flash[:danger] = "Only admin is allowed to do that"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options={ size: 150 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
        image_tag(gravatar_url, alt: user.username, class: 'img-circle img-responsive')
    end
end

app/views/articles/_article.erb
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <div class="well well-lg">
            <div id="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div id="article-body">
                <%= truncate(article.description, length: 300) %>
            </div>
            <div class="article-meta-details">
                <small>Created by: <%= link_to(article.user.username, user_path(article.user)) if article.user %>, 
                                <%= time_ago_in_words(article.created_at) %> ago 
                                last updated: <%= time_ago_in_words(article.updated_at) %> </small>
            </div>
            <% if article.categories.any? %>
                    <p>Categories: <%= render article.categories %></p>
                <% end %>
            <div class="buttons">
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <%= link_to "Edit", edit_article_path(article), class: 'btn btn-primary btn-xs' %>
                <% end %>
                <%= link_to "Delete", article_path(article), 
                          method: :delete, 
                          class: 'btn btn-danger btn-xs',
                          data: { confirm: 'Are you sure?' }
                          %>
            </div>
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<h1 class="text-center"><%= form_name %></h1>
<%= form_for article, class: 'form-horizontal' do |f| %>
    <div class='form-group'>
        <%= f.label :title %><br />
        <%= f.text_field :title, placeholder: 'Title of article', class: 'form-control' %>
    </div>
    <div class='form-group'>
        <%= f.label :description %><br />
        <%= f.text_area :description, placeholder: 'Body of article', class: 'form-control', rows: 10, cols: 15 %><br />
    </div>
    <div class="form-group">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <%= cb.label(class: 'checkbox-inline') { cb.check_box(class: 'checkbox') + cb.text } %>
        <% end %>
    </div>
    <div class='form-group'>
        <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <% if @article.errors.any? %>
                <%= render 'shared/errors', target: @article %>
            <% end %>
            <%= render 'form', article: @article, form_name: 'Edit article' %>
            <%= link_to '[Cancel request and return to articles listing]', articles_path, class: 'text-center' %>
        </div>
    </div>
</div>

app/views/articles/index.html.erb
<div class="container">
    <h1 class="text-center" id="page-title">Listing all articles</h1>
    <%= render @articles, locals: { cur_user: current_user } %>
    <div class="row">
        <div class="text-center">
            <%= will_paginate %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <% if @article.errors.any? %>
                <%= render 'shared/errors', target: @article %>
            <% end %>
            <%= render 'form', article: @article, form_name: 'Create new article' %>
            <%= link_to '[Cancel request and return to articles listing]', articles_path, class: 'text-center' %>
        </div>
    </div>
</div>

app/views/articles/show.html.erb
<%= render @article %>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<h1 class="text-center"><%= form_name %></h1>
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <% if @category.errors.any? %>
                <%= render 'shared/errors', target: @category %>
        <% end %>
        <%= form_for @category, class: 'form-horizontal' do |f| %>
            <div class="form-group">
                <%= f.label :name %><br />
                <%= f.text_field :name, placeholder: 'Category', class: 'form-control' %>
            </div>
            <div class="form-group text-center">
                <%= f.submit 'Create new article', class: 'btn btn-large btn-primary' %>
            </div>
        <% end %>
    </div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', form_name: "Editing category #{@category.name}" %>

app/views/categories/index.html.erb
<h1 class="text-center">Listing all categories</h1>
<% @categories.each do |category| %>
    <div class="row">
        <div class="col-xs-4 col-xs-offset-4 well">
            <%= link_to category.name, category_path(category), class: 'category__title' %>
        </div>
    </div>
<% end %>
<div class="row">
    <div class="text-center">
        <%= will_paginate @categories %>
    </div>
</div>

app/views/categories/new.html.erb
<%= render 'form', form_name: "New category" %>

app/views/categories/show.html.erb
<h1 class="text-center">Listing article for <%= @category.name %> category</h1>
<%= render @articles, locals: { cur_user: current_user } %>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
    <footer class="footer">
        Copyright &copy; Ruby on Rails blog engine application by 
        <a href="https://github.com/OlegStotsky">Oleg Stotsky</a>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% class_name = "alert alert-#{name} alert-dismissable fade in" %>
  <div class="<%= class_name %>">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to 'Rails Blog', root_path, class: 'navbar-brand', id: 'logo' %>
    </div>
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Articles', articles_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <% if logged_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Actions<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to 'New Article', new_article_path %></li>
                        <li><%= link_to 'New Category', new_category_path if current_user.admin? %></li>
                    </ul>
                </li>
            <% end %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Categories<span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <% Category.all.each do |category| %>
                        <li><%= link_to category.name, category_path(category) %></li>
                    <% end %>
                </ul>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
                <li>
                    <%= link_to logout_path, method: 'delete' do %>
                        <span class="glyphicon glyphicon-log-out"></span>Log Out
                    <% end %>
                </li>
                <li class="dropdown">
                        <a href="#" 
                            class="dropdown-toggle" 
                            data-toggle="dropdown" 
                            role="button" aria-haspopup="true" 
                            aria-expanded="false">
                                Your Profile <%= "(Admin)" if current_user.admin? %>
                                <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
                            <li><%= link_to "View your profile", user_path(current_user) %></li>
                        </ul>
                </li>
            <% else %>
                <li><a href=<%= signup_path %>><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                <li><a href=<%= login_path %>><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="jumbotron text-center">
        <h1 class="">Rails Blog Engine</h1>
        <% if session[:user_id] %>
            <%= link_to 'Log out', logout_path, class: 'btn btn-primary btn-lg', method: 'delete' %>
        <% else %>
            <%= link_to 'Signup', signup_path, class: 'btn btn-primary btn-lg' %>
            <%= link_to 'Log in', login_path, class: 'btn btn-primary btn-lg' %>
        <% end %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% target.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= msg %>
    </div>
<% end %>

app/views/users/_form.html.erb
<h1 class="text-center"><%= form_name %></h1>
<%= form_for user, class: 'form-horizontal' do |f| %>
    <div class="form-group" %>
        <%= f.label :username %></br>
        <%= f.text_field :username, placeholder: 'Username', class: 'form-control' %>
    </div>
    <div class="form-group" %>
        <%= f.label :email %></br>
        <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
    </div>
    <div class='form-group' %>
        <%= f.label :password %></br>
        <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
    </div>
    <div class='text-center'>
        <%= f.submit button_text, class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <% if @user.errors.any? %>
            <%= render 'shared/errors', target: @user %>
        <% end %>
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <%= render 'form', user: @user, form_name: 'Edit User', button_text: 'Update Account' %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <h1 class="text-center">All Users</h1>
    <% @users.each do |user| %>
    <ul class="listing">
        <div class="row">
            <div class="well col-md-4 col-md-offset-4" align="center">
                <li><%= link_to gravatar_for(user), user_path(user) %></li>
                <li class="article-title">
                    <%= link_to user.username, user_path(user) %>
                </li>
                <li>
                    <small><%= pluralize(user.articles.count, "articles") if user.articles %></small>
                </li>
                <% if logged_in? && current_user.admin? %>
                    <li>
                        <%= link_to "Delete this user", 
                                user_path(user), 
                                method: :delete, 
                                class: 'btn btn-danger btn-xs',
                                data: { confirm: "Are you sure you want to delete this user and all his articles?" } 
                        %>
                    </li>
                <% end %>
            </div>
        </div>
    </ul>
    <% end %>
    <div class="text-center">
        <%= will_paginate %>
    </div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <% if @user.errors.any? %>
                <%= render 'shared/errors', target: @user %>
            <% end %>
            <%= render 'form', user: @user, form_name: 'Create New User', button_text: 'Sign Up' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <h1 class="text-center">Welcome to <%= @user.username %>'s page</h1>
    <h4 class="text-center"><%= @user.username %>'s articles </h4>
    <div class="user__profile_image">
        <%= gravatar_for(@user) %>
    </div>
    <%= render partial:'articles/article', collection:@user_articles %>
    <div class="text-center">
        <%= will_paginate @user_articles %>
    </div>
</div>